front_category_create:
    path: /category
    defaults: { _controller: AppBundle:Front\Category:create }
    methods: [GET]

front_category_store:
    path: /category
    defaults: { _controller: AppBundle:Front\Category:store }
    methods: [POST]

front_category_all:
    path: /categories
    defaults: { _controller: AppBundle:Front\Category:all }
    methods: [GET]

front_category_edit:
    path: /category/edit/{id}
    defaults: { _controller: AppBundle:Front\Category:edit }
    methods: [GET]
    requirements:
        id: '\d+'

front_category_update:
    path: /category/edit/{id}
    defaults: { _controller: AppBundle:Front\Category:update }
    methods: [PUT]
    requirements:
        id: '\d+'

front_category_delete:
    path: /category/{id}
    defaults: { _controller: AppBundle:Front\Category:delete }
    methods: [DELETE]
    requirements:
        id: '\d+'
