front_event_create:
    path: /event
    defaults: { _controller: AppBundle:Front\Event:create }
    methods: [GET]

front_event_store:
    path: /event
    defaults: { _controller: AppBundle:Front\Event:store }
    methods: [POST]

front_event_get:
    path: /event/{id}
    defaults: { _controller: AppBundle:Front\Event:get }
    methods: [GET]
    requirements:
        id: '\d+'

front_event_edit:
    path: /event/edit/{id}
    defaults: { _controller: AppBundle:Front\Event:edit }
    methods: [GET]
    requirements:
        id: '\d+'

front_event_update:
    path: /event/edit/{id}
    defaults: { _controller: AppBundle:Front\Event:update }
    methods: [PUT]
    requirements:
        id: '\d+'

front_event_delete:
    path: /event/{id}
    defaults: { _controller: AppBundle:Front\Event:delete }
    methods: [DELETE]
    requirements:
        id: '\d+'
