AppBundle\Entity\AuthCode:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        client:
            targetEntity: AppBundle\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: AppBundle\Entity\User
